MACHINE_BOX = 'ubuntu/focal64'
MACHINE_NAME = 'focal64'

Vagrant.configure('2') do |config|
  config.vm.define(MACHINE_NAME) do |vagrant|
    vagrant.vm.box = MACHINE_BOX
    vagrant.vm.hostname = MACHINE_NAME
    vagrant.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2200, auto_correct: false)
    vagrant.vm.network('forwarded_port', id: 'http', guest: 8000, host: 8000)
  end
end