MACHINE = 'contrib-buster-64'

Vagrant.configure('2') do |config|
  config.vm.define(MACHINE) do |custom_config|
    custom_config.vm.hostname = MACHINE
    custom_config.vm.box = 'debian/contrib-buster64'
    custom_config.vm.network 'forwarded_port', guest: 80, host: 8080
  end

  config.vm.provision('docker') do |docker|
    docker.run('nginx')
  end
end