---

- name: Configure webserver with NGINX and TLS
  hosts: webservers
  become: true
  become_user: root
  gather_facts: false

#  vars:
#    tls_dir: /etc/nginx/ssl/
#    key_file: nginx.key
#    key_file: nginx.key
#    cert_file: nginx.crt
#    conf_file: /etc/nginx/sites-available/default
#    server_name: localhost

  # Un'alternativa più elegante alle "vars" sopra se ho molte variabili.
  vars_files:
    - nginx.yml

  handlers:
    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

  tasks:
    - name: Ensure NGINX is installed
      package:
        name: nginx
        update_cache: true

    - name: Create directories for TLS certificates
      file:
        path: "{{ tls_dir }}"
        state: directory
        mode: "0750"
      notify: Restart NGINX

    - name: Copy TLS files
      copy:
        src: "{{ item }}"
        dest: "{{ tls_dir }}"
        mode: "0600"
      loop:
        - "{{ key_file }}"
        - "{{ cert_file }}"
      notify: Restart NGINX

    - name: Manage NGINX config template
      template:
        src: nginx.conf.j2
        dest: "{{ conf_file }}"
        mode: "0644"
      notify: Restart NGINX

    - name: Enable configuration
      file:
        src: "{{ conf_file }}"
        dest: /etc/nginx/sites-enabled/default
        state: link

    - name: Copy homepage template
      template:
        src: index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: "0644"

    # Serve per forzare l'handler in questo punto, altrimenti girerebbe solo alla fine.
    - name: Restart NGINX
      meta: flush_handlers

    - name: "Test the http://localhost:8080/index.html response"
      delegate_to: localhost
      become: false
      uri:
        url: http://localhost:8080/index.html
        return_content: true
      register: response
      failed_when: "'Questo NGINX è stato configurato grazie ad Ansible' not in response.content"

    - name: "Test the https://localhost:8433/index.html response"
      delegate_to: localhost
      become: false
      uri:
        url: https://localhost:8443/index.html
        validate_certs: false
        return_content: true
      register: response
      failed_when: "'Questo NGINX è stato configurato grazie ad Ansible' not in response.content"

...
