---
# L'ho commentatoperché ho provato a farlo con il ruolo updater e funziona. Bisogna specificare nei meta la dipendenza del ruolo.
# - include_tasks: setup.yml

- name: Ensure Nginx config path exists
  become: true
  file:
    path: "{{ nginx_conf_path }}"
    state: directory
    mode: '755'

- name: Remove default Nginx config file
  become: true
  file:
    path: "{{ nginx_default_path }}/default"
    state: absent

- name: Set the Nginx config file
  become: true
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_available_path }}/nginx.conf"
    mode: "640"
  notify: Restart Nginx
...