MACHINE = 'trusty-64'

Vagrant.configure('2') do |config|
  config.vm.define(MACHINE) do |custom_config|
    custom_config.vm.box = 'ubuntu/trusty64'
    custom_config.vm.hostname = MACHINE
    custom_config.vm.network('private_network', ip: '192.168.56.10')
  end
end