---

- name: Configure some libraries
  hosts: contrib-buster-64
  become: true
  become_user: root

  tasks:
    - name: Ensure NGINX is installed
      package:
        name: nginx
        update_cache: true
...
