---

# Le LOCAL FACT rappresentano la raccolta di informazioni che si trovano in questo path dell'host remoto: /etc/ansible/facts.d
# Devo mettere un file (non eseguibile) con estensione .facts e in formato INI o JSON.
- name: Example Local Facts
  hosts: vagrant
  gather_facts: true

  tasks:
    - name: Gets local facts
      debug:
        var: ansible_local
...