VAGRANT_1 = 'vagrant-1'
VAGRANT_2 = 'vagrant-2'

Vagrant.configure('2') do |config|
  config.ssh.insert_key = false # Usa la stessa chiave per tutte le macchine

  config.vm.define(VAGRANT_1) do |vagrant_1|
    vagrant_1.vm.box = 'debian/contrib-buster64'
    vagrant_1.vm.hostname = VAGRANT_1
    vagrant_1.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2201, auto_correct: false)
    vagrant_1.vm.network('forwarded_port', id: 'http', guest: 80, host: 8081)
    vagrant_1.vm.network('forwarded_port', id: 'https', guest: 443, host: 8441)
    vagrant_1.vm.provision('shell', inline: 'mkdir -p /etc/ansible/facts.d')
    vagrant_1.vm.synced_folder('./data/', '/etc/ansible/facts.d')
  end

  config.vm.define(VAGRANT_2) do |vagrant_2|
    vagrant_2.vm.box = 'ubuntu/focal64'
    vagrant_2.vm.hostname = VAGRANT_2
    vagrant_2.vm.network('forwarded_port', id: 'ssh', guest: 22, host: 2202, auto_correct: false)
    vagrant_2.vm.network('forwarded_port', id: 'http', guest: 80, host: 8082)
    vagrant_2.vm.network('forwarded_port', id: 'https', guest: 443, host: 8442)
  end
end