---

- name: Play-1 for gather variables
  hosts: vagrant # possono essere diversi da ruolo a ruolo
  gather_facts: true

  roles:
    - role: my_gather # Quando invochiamo il ruolo, possiamo anche passargli delle variabili... queste vincono sulle variabili definite nel ruolo stesso, fanno l'override.

- name: Play-2 for messages
  hosts: all # possono essere diversi da ruolo a ruolo
  gather_facts: false

  roles:
    - role: my_message
...
